<?php

return [
    'about' => [
        'en' => [
            'hero_announcement'      => "Announcing our next round of funding.",
            'read_more'              => "Read more",
            'hero_title'             => "Data to enrich your online business",
            'hero_description'       => "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat.",
            'get_started'            => "Get started",
            'learn_more'             => "Learn more",
            'our_story_title'        => "Our Story",
            'our_story_description'  => "Founded on the principles of integrity and innovation, our company has grown into a leader in the industry. We believe in harnessing expertise and leveraging cutting-edge technology to drive meaningful results.",
            'mission_title'          => "Our Mission",
            'mission_description'    => "Our mission is to empower businesses by providing tailored solutions that drive growth, foster innovation, and create lasting value. We are committed to excellence in every endeavor.",
            'vision_title'           => "Our Vision",
            'vision_description'     => "We envision a future where strategic partnerships and innovative solutions converge to transform industries and shape a better, more sustainable world for generations to come.",
            'core_values_title'      => "Our Core Values",
            'integrity'              => "Integrity",
            'integrity_description'  => "We conduct our business with the highest standards of ethics and transparency.",
            'innovation'             => "Innovation",
            'innovation_description' => "Creativity and forward-thinking drive our approach to solving complex challenges.",
            'excellence'             => "Excellence",
            'excellence_description' => "We strive for excellence in every project, ensuring outstanding quality and performance.",
            'join_journey_title'     => "Join Our Journey",
            'join_journey_description' => "Learn more about our vision, our values, and the talented team driving our success.",
            'get_in_touch'           => "Get In Touch",
        ],
        'nl' => [
            'hero_announcement'      => "Aankondiging van onze volgende financieringsronde.",
            'read_more'              => "Lees verder",
            'hero_title'             => "Gegevens om uw online bedrijf te verrijken",
            'hero_description'       => "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat.",
            'get_started'            => "Begin nu",
            'learn_more'             => "Meer informatie",
            'our_story_title'        => "Ons Verhaal",
            'our_story_description'  => "Opgericht op de principes van integriteit en innovatie, is ons bedrijf uitgegroeid tot een leider in de sector. We geloven in het benutten van expertise en het gebruik van geavanceerde technologie om betekenisvolle resultaten te behalen.",
            'mission_title'          => "Onze Missie",
            'mission_description'    => "Onze missie is om bedrijven in staat te stellen door op maat gemaakte oplossingen te bieden die groei stimuleren, innovatie bevorderen en blijvende waarde creëren. We streven naar uitmuntendheid in elke onderneming.",
            'vision_title'           => "Onze Visie",
            'vision_description'     => "Wij zien een toekomst waarin strategische partnerschappen en innovatieve oplossingen samenkomen om industrieën te transformeren en een betere, duurzamere wereld voor toekomstige generaties te creëren.",
            'core_values_title'      => "Onze Kernwaarden",
            'integrity'              => "Integriteit",
            'integrity_description'  => "Wij voeren onze activiteiten uit volgens de hoogste normen van ethiek en transparantie.",
            'innovation'             => "Innovatie",
            'innovation_description' => "Creativiteit en vooruitdenken sturen onze aanpak om complexe uitdagingen op te lossen.",
            'excellence'             => "Uitmuntendheid",
            'excellence_description' => "Wij streven naar uitmuntendheid in elk project en zorgen voor uitstekende kwaliteit en prestaties.",
            'join_journey_title'     => "Doe mee met onze reis",
            'join_journey_description' => "Leer meer over onze visie, onze waarden en het getalenteerde team dat ons succes aandrijft.",
            'get_in_touch'           => "Neem contact op",
        ]
    ],

    'agendaevent' => [
        'title'          => "Agenda",
        'description'    => "Blijf op de hoogte van onze aankomende evenementen.",
        'eventTitle'     => "Evenementen",
        'readMore'       => "Lees verder...",
        'viewEvent'      => "Bekijk evenement",
        'noEvents'       => "Geen evenementen beschikbaar",
        'location'       => "Locatie",
        'register'       => "Aanmelden",
        'close'          => "Sluiten",
    ],

    'contact' => [
        'contactTitle'       => "Neem contact op",
        'contactDescription' => "Heb je vragen? Neem contact met ons op via e-mail, telefoon of bezoek ons op locatie.",
        'visitUs'            => "Bezoek ons",
        'chatWithUs'         => "Chat met ons",
        'callUs'             => "Bel ons",
        'ourLocation'        => "Onze Locatie",
        'address'            => "67 Wisteria Way, Croydon South VIC 3136, AU",
        'email'              => "info@yourcompany.com",
        'phoneHours'         => "Ma-Vr 8:00 - 17:00",
        'phoneNumber'        => "(+995) 555-55-55-55",
        'sendMessage'        => "Stuur ons een bericht",
        'name'               => "Naam",
        'emailAddress'       => "E-mailadres",
        'phoneNumberField'   => "Telefoonnummer",
        'typeMessage'        => "Typ hier je bericht",
        'agreePrivacy'       => "Ik ga akkoord met de",
        'privacyPolicy'      => "Privacy Policy",
        'sendButton'         => "Bericht versturen",
        'followUs'           => "Volg ons op",
    ],

    'masterclass' => [
        'masterclassTitle'       => "Masterclass",
        'masterclassDescription' => "Doe mee met onze exclusieve masterclass en leer van experts.",
        'enrollNow'              => "Meld je nu aan",
        'whatYouWillLearn'       => "Wat Je Gaat Leren",
        'learnStrategies'        => "Innovatieve Strategieën",
        'learnApplications'      => "Praktische toepassingen",
        'learnGrowth'            => "Persoonlijke Groei",
    ],

    'private-equity' => [
        'heroTitle'        => "Private Equity",
        'heroDescription'  => "Investeer slim en creëer duurzame waarde.",
        'investmentTitle'  => "Onze investeringsstrategie",
        'investment1'      => "Uitgebreid Netwerk",
        'investment2'      => "Deskundige Analyse",
        'investment3'      => "Strategische Groei",
        'investment4'      => "Langdurige Waardecreatie",
        'testimonialsTitle' => "Wat Onze Klanten Zeggen",
        'partnersTitle'    => "Onze Partners",
        'insightsTitle'    => "Laatste Inzichten",
    ],

    'real-estate' => [
        'heroTitle'        => "Real Estate",
        'heroDescription'  => "Investeren in vastgoed voor langetermijngroei.",
        'investmentFocus'  => "Onze Investeringsfocus",
        'investment1'      => "Luxe Residenties",
        'investment2'      => "Commerciële Panden",
        'investment3'      => "Hospitality & Korte Termijn Verhuur",
        'investment4'      => "Ontwikkelingsprojecten",
        'whyInvestTitle'   => "Waarom Investeren?",
    ],

    'webinar' => [
        'heroTitle'        => "Webinar",
        'heroDescription'  => "Neem deel aan onze live webinars en leer van experts.",
        'registerNow'      => "Registreer Nu",
    ]
];
